HH-62743 add setting percentage_of_readfunction_posts
hhru/tornado pull request #8
Opened 2016-09-16 09:14 UTC by Kapiton42

Добавил возможность использовать postfields  вместо readfunction для пост-запросов curl-клиентом

2016-09-16 12:41 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +            if request.start_time * 100 % 100 < options.percentage_of_readfunction_posts:
так у тебя при сплите 50/50 будет полсекунды один механизм, полсекунды другой
это, конечно, не очень критично, но наверное * 1000 будет получше

2016-09-16 12:46 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +                if request.method == "POST":
эта проверка уже сделана выше

2016-09-16 12:47 UTC, SuminAndrew commented on tornado/curl_httpclient.py
>          curl.setopt(pycurl.READFUNCTION, request_buffer.read)
эти две строчки у тебя ниже, отсюда наверное стоит их удалить

2016-09-16 12:49 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +                curl.setopt(curl.POSTFIELDS, request.body)
pycurl.POSTFIELDS ?

2016-09-16 12:50 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +                                         curl.getinfo(pycurl.TOTAL_TIME),
тут TOTAL_TIME только интересен?

2016-09-16 12:52 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +        if curl.type_of_post_data != "not_post":
лучше наверное достать эту инфу из curl.getinfo(pycurl.POST), curl.getinfo(pycurl.READFUNCTION), curl.getinfo(pycurl.POSTFIELDS), если это возможно, конечно, и не использовать временного хранилища

2016-09-16 12:53 UTC, SuminAndrew requested changes

2016-09-16 13:06 UTC, Kapiton42 commented on tornado/curl_httpclient.py
> +        if curl.type_of_post_data != "not_post":
он от этого огорчается и выдает ексепшен ValueError: invalid argument to getinfo

2016-09-16 13:10 UTC, Kapiton42 commented on tornado/curl_httpclient.py
> +                                         curl.getinfo(pycurl.TOTAL_TIME),
ну в принципе да, его же хватит для понимания, что поменялось

2016-09-16 13:12 UTC, Kapiton42 commented on tornado/curl_httpclient.py
> +                curl.setopt(curl.POSTFIELDS, request.body)
поправил

2016-09-16 13:12 UTC, Kapiton42 commented on tornado/curl_httpclient.py
> +                if request.method == "POST":
поправил

2016-09-16 13:12 UTC, Kapiton42 commented on tornado/curl_httpclient.py
> +            if request.start_time * 100 % 100 < options.percentage_of_readfunction_posts:
поправил

2016-09-16 13:12 UTC, Kapiton42 commented on tornado/curl_httpclient.py
>          curl.setopt(pycurl.READFUNCTION, request_buffer.read)
поправил

2016-09-16 13:20 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +        if curl.type_of_post_data != "not_post":
да, видимо так нельзя, жаль

2016-09-16 13:21 UTC, SuminAndrew commented on tornado/curl_httpclient.py
> +                curl.setopt(pycurl.POSTFIELDS, request.body)
тут надо скорее всего тоже utf8(request.body)

2016-09-16 14:33 UTC, SuminAndrew approved these changes

2016-09-20 08:35 UTC, SuminAndrew commented on tornado/curl_httpclient.py
>          if request.method == "POST":
я бы сделал так:
```python
if request.method == "POST" and request.start_time * 1000 % 100 >= options.percentage_of_readfunction_posts:
    # используем POSTFIELDS
else:
    # старая ветка в нетронутом состоянии
```

2016-09-20 08:37 UTC, SuminAndrew commented on tornado/curl_httpclient.py
>          else:
вот эта ветка какая-то нерабочая получается

2016-09-26 17:13 UTC, merged